repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: pretty-format-json
        exclude: "tsconfig.json"
        args: [--autofix]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--disable, MD013]
  - repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: 'v0.60.0'
    hooks:
      - id: scss-lint
  - repo: local
    hooks:
      - id: frontend
        name: Lint Frontend
        language: system
        pass_filenames: false
        require_serial: true
        entry: yarn --cwd frontend format
      - id: backend
        name: Lint Backend
        language: system
        pass_filenames: false
        require_serial: true
        entry: yarn --cwd backend format
